# epanet ensemble simulation stack
# sam@citilogics.com
#
#
# - redis: serve the job queue
# - fileStore: file store accessible to all workers
# - worker: execute simulation, upload results
# - redis-dashboard: visualize worker progress
# - influx: collect results
# - dash: visualize results
#
## TO_DO:
## - finalize the deploy configuration (swarm mode)
##

version: '3.3'
services:

  queue:
    image: redis:3.2
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 6379:6379

  file_store:
    image: nginx
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - file_store:/usr/share/nginx/html:ro

  dash:
    image: grafana/grafana:5.1.3
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 3000:3000
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_PASSWORD=whew.semi.amiably
    volumes:
      - dash:/var/lib/grafana

  influx:
    image: influxdb:1.5.2
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      #- INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
      - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0
    volumes:
      - influx:/var/lib/influxdb

  worker:
    image: openwateranalytics/ensemble_worker
    environment:
      - FILE_HOST=file_store
      - REDIS_HOST=queue
    deploy:
      mode: global # one instance per node
      placement:
        constraints: [node.role != manager] # every non-manager node
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'

  queue-dash:
    image: robbieclarken/lightweight-rq-dashboard
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 9181:9181
    command: -H queue

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  influx:
  dash:
  file_store:
